### ISSUE TITLE
Does ROPNet is suitable for large scene datasets like 3dmatch or kitti?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [zhulf0804/ROPNet#1]
Is there any tests or experiments?

**Comment by zhulf0804** [comment]
Unfortunately, we may not apply ROPNet directly to 3DMatch or KITTI without modifications. Because the design of network structure and loss function for large datasets was not considered initially.

**Comment by Yellowshuohahaha** [comment]
Thanks for your reply. It is still a excellent work!
