### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by zhaiqing** [zhulf0804/ROPNet#2]
Hello, can you post a pre-trained model ?

**Comment by zhulf0804** [comment]
Hi, I uploaded the pre-trained weights and training logs for Table 2, 3 in the paper on the Baidu Disk.

The link is https://pan.baidu.com/s/18ITMWFz-nXH8Jt8CRKg-4g with password `s486`.

But I am not sure whether the weights for Table 1 can be found.

**Comment by zhaiqing** [comment]
thank you very much
